package View.SpareParts;


import View.Invoice.InvoicesUI;
import View.LogInUI;
import View.MainUI;
import View.MonthlyReport.MonthlyReport;

import View.Suppliers.SupplierUI2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import View.SpareParts.AddSparePartsUI;

/**
 *
 * @author theCodeMonster
 */
public class SparePartsUI extends javax.swing.JFrame {
    
    AddSparePartsUI addSp;
    
    private static final String URL = "jdbc:mysql://localhost/SparePartsDB";
    private static final String user = "root";
    private static final String password = "";

    /**
     * Creates new form ManageSPUI
     */
    public SparePartsUI() {
        initComponents();

        addSp = new AddSparePartsUI();
//        setExtendedState(MAXIMIZED_BOTH);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        addSparePartsButton = new com.k33ptoo.components.KButton();
        displaySparePartsButton = new com.k33ptoo.components.KButton();
        addSparePartsText = new javax.swing.JLabel();
        displaySparePartsText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Gill Sans", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manage Spare Parts");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 590, 100));

        kButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kButton1.setText("Return");
        kButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        kButton1.setkBorderRadius(50);
        kButton1.setkEndColor(new java.awt.Color(153, 0, 153));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(102, 0, 102));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(153, 0, 153));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 120, 40));

        addSparePartsButton.setBorder(null);
        addSparePartsButton.setText("Add ");
        addSparePartsButton.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        addSparePartsButton.setkBorderRadius(50);
        addSparePartsButton.setkEndColor(new java.awt.Color(155, 68, 25));
        addSparePartsButton.setkHoverEndColor(new java.awt.Color(255, 204, 51));
        addSparePartsButton.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        addSparePartsButton.setkHoverStartColor(new java.awt.Color(255, 102, 51));
        addSparePartsButton.setkPressedColor(new java.awt.Color(255, 153, 153));
        addSparePartsButton.setkStartColor(new java.awt.Color(155, 68, 25));
        addSparePartsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addSparePartsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addSparePartsButtonMouseExited(evt);
            }
        });
        addSparePartsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSparePartsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addSparePartsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 130, 50));

        displaySparePartsButton.setText("Display");
        displaySparePartsButton.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        displaySparePartsButton.setkBorderRadius(50);
        displaySparePartsButton.setkEndColor(new java.awt.Color(0, 153, 51));
        displaySparePartsButton.setkHoverColor(new java.awt.Color(153, 255, 102));
        displaySparePartsButton.setkHoverEndColor(new java.awt.Color(153, 255, 51));
        displaySparePartsButton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        displaySparePartsButton.setkHoverStartColor(new java.awt.Color(204, 255, 0));
        displaySparePartsButton.setkPressedColor(new java.awt.Color(204, 255, 204));
        displaySparePartsButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        displaySparePartsButton.setkStartColor(new java.awt.Color(0, 153, 0));
        displaySparePartsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                displaySparePartsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                displaySparePartsButtonMouseExited(evt);
            }
        });
        displaySparePartsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaySparePartsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displaySparePartsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 150, 50));

        addSparePartsText.setFont(new java.awt.Font("Grantha Sangam MN", 1, 14)); // NOI18N
        addSparePartsText.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(addSparePartsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 390, 40));

        displaySparePartsText.setFont(new java.awt.Font("Grantha Sangam MN", 1, 14)); // NOI18N
        displaySparePartsText.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(displaySparePartsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohamedazwar/Desktop/OOP Project/Photos/Spare-Parts-2.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        MainUI main = new MainUI();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void addSparePartsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSparePartsButtonActionPerformed

        AddSparePartsUI addParts = new AddSparePartsUI();
        addParts.setVisible(true);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(URL, user, password);
            
            Statement st = conn.createStatement();
            // sql query
            String query = "SELECT * FROM SparePartsDB.SpareParts";
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()){
                
                String spID = String.valueOf(rs.getInt("SparePart ID"));
                String spName = rs.getString("Name of Item");
                String spCategory = rs.getString("Category");
                String spBrand = rs.getString("Brand");
                String spQuantity = String.valueOf(rs.getInt("Quantity"));
                
                String[] tbData = {spID, spName, spCategory, spBrand, spQuantity};
                DefaultTableModel dtm2 = (DefaultTableModel) addSp.jTable1.getModel();
                dtm2.addRow(tbData);
            }
            
            
        } catch (Exception ex){
            System.err.println(ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_addSparePartsButtonActionPerformed

    private void displaySparePartsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaySparePartsButtonActionPerformed
        DisplaySparePartsUI displayParts = new DisplaySparePartsUI();
        displayParts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_displaySparePartsButtonActionPerformed

    private void addSparePartsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSparePartsButtonMouseEntered
        addSparePartsText.setText("Click this Button to Add a Spare Parts details to Store");
    }//GEN-LAST:event_addSparePartsButtonMouseEntered

    private void addSparePartsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSparePartsButtonMouseExited
        addSparePartsText.setText("");
    }//GEN-LAST:event_addSparePartsButtonMouseExited

    private void displaySparePartsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displaySparePartsButtonMouseEntered
        displaySparePartsText.setText("Click this Button to Display Spare Parts details in the Store");
    }//GEN-LAST:event_displaySparePartsButtonMouseEntered

    private void displaySparePartsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displaySparePartsButtonMouseExited
        displaySparePartsText.setText("");
    }//GEN-LAST:event_displaySparePartsButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SparePartsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton addSparePartsButton;
    private javax.swing.JLabel addSparePartsText;
    private com.k33ptoo.components.KButton displaySparePartsButton;
    private javax.swing.JLabel displaySparePartsText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private com.k33ptoo.components.KButton kButton1;
    // End of variables declaration//GEN-END:variables
}
